### ISSUE TITLE
Rotate touchscreen and wacom pen too

### ISSUE THREAD

**Issue by adrfantini** [mrquincle/yoga-900-auto-rotate#1]
This program works beautifully on my late 2017 Acer Spin 5. However, the touchscreen and the wacom surface are not rotated according to the orientation. Can this be done?

Basically one should do, e.g. (for the normal orientation):
`xinput set-prop "ELAN Touchscreen" "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1`
`xinput set-prop "ELAN Touchscreen Pen" "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1`
Other coordinate matrixes:
left: `0 -1 1 1 0 0 0 0 1`
right: `0 1 0 -1 0 1 0 0 1`
inverted: `-1 0 1 0 -1 1 0 0 1`

**Comment by mrquincle** [comment]
The touch on the screen on the yoga is rotated simultaneously. Perhaps you mean the touchpad? If you fold the yoga this gets disabled. 

It wouldn't be wise to start setting this up for all possible pads and surfaces. Is there a standard way I can rotate it with the screen?

**Comment by adrfantini** [comment]
No, I really mean the touchscreen (+wacom surface). Can you point me to where the touch rotation happens in the .c program? I know nothing of C unfortunately, but maybe I can figure it out.
There is no way afaik to do both screen and touchscreen rotation in one single command.

**Comment by adrfantini** [comment]
Maybe one could use this?
`https://linux.die.net/man/3/xichangeproperty`

**Comment by mrquincle** [comment]
True.

1. You will need to call something like this:

```  
        prop_float = XInternAtom(display, "FLOAT", False);
        if (prop_float == None) {
            fprintf(stderr, "ERROR : Float atom not found..\n");
            return FAILURE;
        }
        prop = XInternAtom(display, "Coordinate Transformation Matrix", False);
        if (prop == None) {
            fprintf(stderr, "ERROR : Coordinate Transformation Matrix property not found.\n");
            return FAILURE;
        }
        XIChangeProperty(display, device_id, prop, prop_float, 32, PropModeReplace, coordinates, 9);
```

2. You will need to find which display / device_id you want to use. It's best not to hardcode this in the C file, but to include it as an optional argument.

3. Adjust locally your auto-rotate.service file to include the proper pointer from `xinput --list`. 

4. Make sure the daemon does not break if your Wacom surface is not attached on boot.

5. Make sure the daemon does its work also if the Wacom surface is hotplugged.

6. Check if other things are also rotated with the coordinate system, swipe with multiple fingers, swipe along the edge for scrolling, etc.

**Comment by adrfantini** [comment]
I've been playing with it. I can't find a way to get the device id from the name, do you know if that's possible?

Also I keep banging my head about why with `xinput` I can change the transformation matrix for "ELAN Touchscreen" but not for "ELAN Touchscreen Pen", despite both having the "Coordinate Transformation Matrix" property...

**Comment by rajeeshknambiar** [comment]
> The touch on the screen on the yoga is rotated simultaneously.

In my Yoga 900, screen rotation works beautifully, but touchscreen rotation doesn't (neither left-up, nor right-up nor bottom-up).
Does XRRSetScreenConfig() automatically rotate input too? I thought xinput rotation needs to be done separately.

**Comment by mrquincle** [comment]
@rajeeshknambiar That's awkward! For me the touch screen rotates definitely with the screen. It is only the touch pad that does not rotate simultaneously.

```
xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ELAN21EF:00 04F3:21EF                   	id=10	[slave  pointer  (2)]
⎜   ↳ SYNA2B29:00 06CB:77C6                   	id=9	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Ideapad extra buttons                   	id=11	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
```

My kernel is not that new by the way, just 4.10.4 (from March).

**Comment by mrquincle** [comment]
@adrfantini I can both adjust my touch screen (id=10) and my touch pad (id=9) with xinput.

```
xinput set-prop 9 "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1 
xinput set-prop 10 "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1 
```

**Comment by rajeeshknambiar** [comment]
This is what I have (Elantech touchscreen id is identical):
```  xinput 
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ Synaptics TM3066-002                      id=10   [slave  pointer  (2)]
⎜   ↳ ELAN21EF:00 04F3:21EF                     id=11   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Video Bus                                 id=7    [slave  keyboard (3)]
    ↳ Power Button                              id=8    [slave  keyboard (3)]
    ↳ Lenovo EasyCamera: Lenovo EasyC           id=9    [slave  keyboard (3)]
    ↳ Ideapad extra buttons                     id=12   [slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard              id=13   [slave  keyboard (3)```

And the kernel version is 4.14.6

**Comment by mrquincle** [comment]
Okay, guys check the code. :-)

It should iterate to all devices that are of XITouchClass or XIValueClass and tries to rotate it accordingly. It works for my touch pad (my touch screen was already working). To see which classes you need use `xinput list --long`.

**Comment by rajeeshknambiar** [comment]
Just tested the updated code.
Normal, left-up & right-up works fine! \o/
Unfortunately, bottom-up still has the touchscreen wrong.

**Comment by mrquincle** [comment]
Check the code: https://github.com/mrquincle/yoga-900-auto-rotate/blob/master/auto-rotate.c#L223.

**Comment by rajeeshknambiar** [comment]
Just tested the latest code, but it resulted in the same behavior for upside down. Coord. Trans. Matrix is same as in previous comment.

But when I commented out line 223 and uncommented 222, it works beautifully. Touchscreen is correctly rotated in all rotation modes!
I have no idea why it didn't work previously. Thanks a lot for your help!!

**Comment by adrfantini** [comment]
Sorry for being late.
Just tested on my Acer Spin 5, I have the same behaviour as @rajeeshknambiar 

By commenting 223 and uncommenting 222 it is PERFECT :)

**Comment by georgewhewell** [comment]
Thanks for this cool software! As others, I get perfect behavior on my X1 Yoga using `rotate180` instead of `reflectX`
